<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="62" started-at="2018-06-23T20:41:57Z" finished-at="2018-06-23T20:41:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="62" started-at="2018-06-23T20:41:57Z" finished-at="2018-06-23T20:41:57Z">
      <class name="FirstPackage.FirstClassInFirstPackage">
        <test-method status="FAIL" signature="firstMethodFirstClassFirstPackage()[pri:1, instance:FirstPackage.FirstClassInFirstPackage@7823a2f9]" name="firstMethodFirstClassFirstPackage" duration-ms="32" started-at="2018-06-24T02:11:57Z" finished-at="2018-06-24T02:11:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at FirstPackage.FirstClassInFirstPackage.firstMethodFirstClassFirstPackage(FirstClassInFirstPackage.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- firstMethodFirstClassFirstPackage -->
        <test-method status="PASS" signature="SecondMethodFirstClassFirstPackage()[pri:2, instance:FirstPackage.FirstClassInFirstPackage@7823a2f9]" name="SecondMethodFirstClassFirstPackage" duration-ms="0" started-at="2018-06-24T02:11:57Z" finished-at="2018-06-24T02:11:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SecondMethodFirstClassFirstPackage -->
      </class> <!-- FirstPackage.FirstClassInFirstPackage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
